### ISSUE TITLE
Problem with the installation (using cmake and make)

### ISSUE THREAD

**Issue by MohamedNennouche** [UCaNLabUMB/gr-owc#1]
Hi, 

I would like to thank you for this work, it will certainly serve many research teams in the field of wireless optics. I wanted to install your module using cmake and make, but when I wanted to build the project with make it gave me this error : 
![image](https://github.com/UCaNLabUMB/gr-owc/assets/58011042/5ea66a3f-f9a5-4907-9b0a-168cbca71bc1)

When I open the file with my editor (VSCode) it tells me that there is no suitable user-defined conversion of "std::shared_ptr<gr::owc::OWC_Channel_relative_impl>" en "gr::owc::OWC_Channel_relative::sptr" (aka "boost::shared_ptr<gr::owc::OWC_Channel_relative>")

How can I fix that? 

Thank you very much

**Comment by mikerahaim** [comment]
Hello! Thanks for the interest in this work. What version of GNURadio are you working with? This library is currently only compatible with GNURadio 3.8, but we are planning to update over the summer to get it working with GNURadio 3.10.

**Comment by MohamedNennouche** [comment]
Oh yeah, I have GNURadio 3.10, I will downgrade my GNURadio and try again, thank you very much !

**Comment by MohamedNennouche** [comment]
Small update: I've downgraded my GNURadio to 3.8 and everything's working fine, thanks!
